#!/bin/bash
set -e

# Generate a .env file from environment variables (e.g., Hugging Face Secrets)
# By default, capture the common keys this app uses. Override with ENV_KEYS.
ENV_PATH=${ENV_PATH:-"/app/.env"}
KEYS=${ENV_KEYS:-"SECRET_KEY DATABASE_URL PORT"}

# Try to write to ENV_PATH, fall back to /tmp if not writable
if ! ( mkdir -p "$(dirname "$ENV_PATH")" >/dev/null 2>&1 && touch "$ENV_PATH" >/dev/null 2>&1 ); then
  echo "[warn] Cannot write to $ENV_PATH; falling back to /tmp/.env" >&2
  ENV_PATH="/tmp/.env"
  : > "$ENV_PATH"  # ensure file exists
fi

echo "# Generated by docker-entrypoint.sh" > "$ENV_PATH"
for key in $KEYS; do
  val=$(printenv "$key")
  if [ -n "$val" ]; then
    printf "%s=%s\n" "$key" "$val" >> "$ENV_PATH"
  fi
done

# Export path so the app can load it explicitly if needed
export DOTENV_FILE="$ENV_PATH"

# Apply PostgreSQL database migrations
if command -v alembic >/dev/null 2>&1; then
  echo "[info] Starting PostgreSQL database migration process..."
  
  # Validate DATABASE_URL is provided
  if [ -z "$DATABASE_URL" ]; then
    echo "[error] DATABASE_URL environment variable is required for PostgreSQL connection" >&2
    exit 1
  fi
  
  # Wait for PostgreSQL to be ready
  echo "[info] Detected PostgreSQL connection, waiting for database to be ready..."
  echo "[debug] DATABASE_URL format: ${DATABASE_URL:0:50}..." # Show first 50 chars for debugging
  
  # Extract connection details from DATABASE_URL with improved parsing
  # Handle various PostgreSQL URL formats: postgresql://user:pass@host:port/db
  DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:/]*\)[:/].*/\1/p')
  DB_PORT=$(echo "$DATABASE_URL" | sed -n 's/.*:\([0-9]*\)\/.*/\1/p')
  
  # Fallback: if no port found, try to extract from after the host
  if [ -z "$DB_PORT" ]; then
    DB_PORT=$(echo "$DATABASE_URL" | sed -n 's/.*@[^:]*:\([0-9]*\).*/\1/p')
  fi
  
  # Default PostgreSQL port if still not found
  if [ -z "$DB_PORT" ]; then
    DB_PORT="5432"
  fi
  
  # If no host found, skip the connection check (might be a different format)
  if [ -n "$DB_HOST" ] && [ "$DB_HOST" != "localhost" ] && [ "$DB_HOST" != "127.0.0.1" ]; then
    echo "[info] Waiting for PostgreSQL at $DB_HOST:$DB_PORT..."
    
    # Try to use netcat if available, otherwise skip connection check
    if command -v nc >/dev/null 2>&1; then
      timeout=30  # Reduced timeout for faster startup
      while [ $timeout -gt 0 ]; do
        if nc -z "$DB_HOST" "$DB_PORT" 2>/dev/null; then
          echo "[info] PostgreSQL is ready!"
          break
        fi
        echo "[info] Waiting for PostgreSQL... ($timeout seconds remaining)"
        sleep 2
        timeout=$((timeout - 2))
      done
      
      if [ $timeout -le 0 ]; then
        echo "[warn] PostgreSQL connection timeout after 30 seconds" >&2
        echo "[warn] This might be due to Hugging Face Spaces network restrictions" >&2
        echo "[info] Proceeding with migration attempt anyway..." >&2
      fi
    else
      echo "[warn] netcat not available, skipping connection check"
      echo "[info] Proceeding with migration attempt..."
    fi
  else
    echo "[info] Skipping PostgreSQL connection check (host: $DB_HOST, port: $DB_PORT)"
    echo "[info] Proceeding with migration attempt..."
  fi
  
  echo "[info] Running database migrations..."
  if ! alembic upgrade head; then
    echo "[error] Alembic migration failed!" >&2
    echo "[error] This might be due to:" >&2
    echo "  - Database connection issues" >&2
    echo "  - Missing database or schema" >&2
    echo "  - Permission issues" >&2
    echo "  - Invalid DATABASE_URL format" >&2
    echo "[info] Attempting to continue without migrations..." >&2
    echo "[warn] Application may not work correctly without proper database setup" >&2
  else
    echo "[info] Database migrations completed successfully!"
  fi
else
  echo "[error] Alembic not found - cannot run database migrations" >&2
  exit 1
fi

exec "$@"
