#!/bin/bash
set -e

# Generate a .env file from environment variables (e.g., Hugging Face Secrets)
# By default, capture the common keys this app uses. Override with ENV_KEYS.
ENV_PATH=${ENV_PATH:-"/app/.env"}
KEYS=${ENV_KEYS:-"SECRET_KEY DATABASE_URL PORT"}

# Try to write to ENV_PATH, fall back to /tmp if not writable
if ! ( mkdir -p "$(dirname "$ENV_PATH")" >/dev/null 2>&1 && touch "$ENV_PATH" >/dev/null 2>&1 ); then
  echo "[warn] Cannot write to $ENV_PATH; falling back to /tmp/.env" >&2
  ENV_PATH="/tmp/.env"
  : > "$ENV_PATH"  # ensure file exists
fi

echo "# Generated by docker-entrypoint.sh" > "$ENV_PATH"
for key in $KEYS; do
  val=$(printenv "$key")
  if [ -n "$val" ]; then
    printf "%s=%s\n" "$key" "$val" >> "$ENV_PATH"
  fi
done

# Export path so the app can load it explicitly if needed
export DOTENV_FILE="$ENV_PATH"

# Load .env file if DATABASE_URL is not set
if [ -z "$DATABASE_URL" ] && [ -f "/app/.env" ]; then
  echo "[info] DATABASE_URL not set, loading from .env file..."
  source /app/.env
  export DATABASE_URL
fi

# Apply PostgreSQL database migrations
if command -v alembic >/dev/null 2>&1; then
  echo "[info] Starting PostgreSQL database migration process..."
  
  # Debug: Show what DATABASE_URL contains
  echo "[debug] DATABASE_URL value: '${DATABASE_URL}'"
  echo "[debug] DATABASE_URL length: ${#DATABASE_URL}"
  echo "[debug] All environment variables containing DATABASE:"
  env | grep -i database || echo "  No DATABASE variables found"
  
  # Validate DATABASE_URL is provided
  if [ -z "$DATABASE_URL" ]; then
    echo "[error] DATABASE_URL environment variable is required for PostgreSQL connection" >&2
    echo "[error]" >&2
    echo "[error] To fix this in Hugging Face Spaces:" >&2
    echo "[error] 1. Go to your Space settings" >&2
    echo "[error] 2. Click on 'Variables and secrets'" >&2
    echo "[error] 3. Add a new secret named 'DATABASE_URL'" >&2
    echo "[error] 4. Set the value to your PostgreSQL connection string" >&2
    echo "[error] 5. Example: postgresql+psycopg://username:password@host:port/database" >&2
    echo "[error]" >&2
    echo "[error] Current environment variables:" >&2
    env | grep -E "(DATABASE|POSTGRES|DB_)" || echo "  No database-related environment variables found" >&2
    exit 1
  fi
  
  # Wait for PostgreSQL to be ready
  echo "[info] Detected PostgreSQL connection, waiting for database to be ready..."
  # Extract connection details from DATABASE_URL
  DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:]*\):.*/\1/p')
  DB_PORT=$(echo "$DATABASE_URL" | sed -n 's/.*:\([0-9]*\)\/.*/\1/p')
  
  if [ -n "$DB_HOST" ] && [ -n "$DB_PORT" ]; then
    echo "[info] Waiting for PostgreSQL at $DB_HOST:$DB_PORT..."
    timeout=60
    while [ $timeout -gt 0 ]; do
      if nc -z "$DB_HOST" "$DB_PORT" 2>/dev/null; then
        echo "[info] PostgreSQL is ready!"
        break
      fi
      echo "[info] Waiting for PostgreSQL... ($timeout seconds remaining)"
      sleep 2
      timeout=$((timeout - 2))
    done
    
    if [ $timeout -le 0 ]; then
      echo "[error] PostgreSQL connection timeout after 60 seconds" >&2
      echo "[error] Please ensure PostgreSQL is running and accessible" >&2
      exit 1
    fi
  fi
  
  echo "[info] Running database migrations..."
  if ! alembic upgrade head; then
    echo "[error] Alembic migration failed!" >&2
    echo "[error] This might be due to:" >&2
    echo "  - Database connection issues" >&2
    echo "  - Missing database or schema" >&2
    echo "  - Permission issues" >&2
    echo "  - Invalid DATABASE_URL format" >&2
    exit 1
  else
    echo "[info] Database migrations completed successfully!"
  fi
else
  echo "[error] Alembic not found - cannot run database migrations" >&2
  exit 1
fi

exec "$@"
